### ISSUE TITLE
CA証明書の有効期限切れでnodejsがインストールできない。

### ISSUE THREAD

**Issue by PiedHarrier** [tobitti0/JoinLogoScpTrialSetLinux#19]
https://deb.nodesource.com/node_14.x%20focal%20InReleaseが404でエラーになる様です

**Comment by tobitti0** [comment]
報告ありがとうございます。
今すぐというわけにはいかないですが、夜に時間があるときに確認します。

**Comment by tobitti0** [comment]
一点確認させてください。
このご報告はどのコードの問題でしょうか。
私の解説記事でしょうか？
よろしくおねがいします

**Comment by PiedHarrier** [comment]
説明不足ですみません。docker ファイルのnode指定を14から16に変えたら上手くbuild出来ました

**Comment by PiedHarrier** [comment]
5chに書いてある方法でうまくbuild出来た

curl  オプションの先頭に-kを追加
curl   -k  -O  -sL

 
curl  -k  -Oでもbuild出来るようですが再起動するとコンテナが壊れるとの話しあり

**Comment by tobitti0** [comment]
@PiedHarrier 
報告あり難うございます。
私の環境下ではエラーが再現できませんでした。
以下がテスト用のファイルです。
```
FROM ghcr.io/tobitti0/docker-avisynthplus:4.3.1-ubuntu2004 as build
MAINTAINER  Tobitti <mail@tobitti.net>
ENV DEBIAN_FRONTEND=noninteractive
ENV NODE_VERSION=14

RUN set -xe && \
    apt-get update && \
    apt-get install --no-install-recommends -y \
      curl

WORKDIR /tmp

# node setup tool
RUN set -xe && \
    cd /tmp && \
    curl -O -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x && \
    mv setup_${NODE_VERSION}.x setup_node.x

RUN bash setup_node.x && \
    apt-get update && \
    apt-get install --no-install-recommends -y nodejs && \
    node -v
```
nodejsのみをインストールし、テストしました。
適当なフォルダに`Dockerfile`として保存し、そのフォルダ内で`docker build -t test .`で正常に動作しました。
過去に生成しているファイル等の影響を受けないように`docker system prune -a`で一時イメージ等を消しましたが、問題ありませんでした。
私の実行環境は下記のとおりです。
```
OS: Ubuntu 20.04.2 LTS x86_64 
Kernel: 5.4.0-81-generic 
Uptime: 55 days, 14 hours, 34 mins 
Packages: 1987 (dpkg), 10 (snap) 
Shell: zsh 5.8 
CPU: Intel i7-4770K (8) @ 3.900GHz 
GPU: NVIDIA GeForce GTX 1050 Ti 
Memory: 1348MiB / 32048MiB 
```
環境情報提供や上記のテスト用Dockerfile等試していただけませんでしょうか。
