### ISSUE TITLE
JLparam_set1のuse_tssplitを有効にするとfatal errorが発生

### ISSUE THREAD

**Issue by yesimanoob** [tobitti0/JoinLogoScpTrialSetLinux#6]
（度々申し訳ありません。LinuxでCMカットができるようになってとっても嬉しくて色々な機能を試したいと思っています。)

`setting/JLparam_set1.csv`に入ってる`use_tssplit`の機能を使ってみたら（バリューを`0`から‘1`に変更：[JLparam_set1.csv.txt](https://github.com/tobitti0/JoinLogoScpTrialSetLinux/files/5348828/JLparam_set1.csv.txt), [obs_param.txt](https://github.com/tobitti0/JoinLogoScpTrialSetLinux/files/5348829/obs_param.txt))、すぐに落ちました：
```
:~/JoinLogoScpTrialSetLinux$ docker-compose run --rm -v ~:/ts join_logo_scp_trial /ts/NTV_video.ts

> join_logo_scp_trial@1.0.0 start /join_logo_scp_trial
> node src/jlse.js "-i" "/ts/NTV_video.ts"

TS spliting ...
TS split done
chapter.auf pre loading program.
usage:
        chapter_exe.exe -v input_avs -o output_txt
params:
        -v 入力画像ファイル
        -a 入力音声ファイル（省略時は動画と同じファイル）
        -m 無音判定閾値（1〜2^15)
        -s 最低無音フレーム数
        -b 無音シーン検索間隔数
        -e 無音前後検索拡張フレーム数
Setting
        video: /join_logo_scp_trial/result/NTV_video/in_org.avs
        audio: (within video source)
        out: /join_logo_scp_trial/result/NTV_video/obs_chapterexe.txt
        mute: 50 seri: 8 bmute: 60 emute: 4
Loading plugins.
Avisynth ERROR: [Fatal]: Failed to avformat_open_input.
(/join_logo_scp_trial/result/NTV_video/in_org.avs, line 2)
放送局：NTV
Avisynth error: [Fatal]: Failed to avformat_open_input.
(/join_logo_scp_trial/result/NTV_video/in_org.avs, line 2)
error: '/join_logo_scp_trial/result/NTV_video/in_org.avs' didn't return a video clip
double free or corruption (fasttop)
auto detect CutMrgIn=9.5 CutMrgOut=11
current set CutMrgIn=9.5 CutMrgOut=11
create_done: /join_logo_scp_trial/result/NTV_video/in_cutcm.avs
create_done: /join_logo_scp_trial/result/NTV_video/in_cutcm_logo.avs
```

`/join_logo_scp_trial/result/NTV_video/in_org.avs`の中身：
```
TSFilePath="/join_logo_scp_trial/result/NTV_video/NTV_video_split.ts"
LWLibavVideoSource(TSFilePath, repeat=true, dominance=1)
AudioDub(last,LWLibavAudioSource(TSFilePath, stream_index=-1, av_sync=true))
```

`/join_logo_scp_trial/result/NTV_video/NTV_video_split.ts`は見つからななかったと思います。
`ts_splitter`は正常に動作しなかった気がします。ファイルパーミッションの問題なんでしょうか？

**Comment by tobitti0** [comment]
`use_tssplit`ですが、実はまだ追加してからDockerファイルを修正していないのです。
[tsdivider](https://github.com/tobitti0/tsdivider)を使って、TSの前後の残骸を削り本編のみ残すという機能です。
この機能はWindows版とは異なるかもしれません。私が勝手にちょうどいいフラグがあるなとそのまま採用したので。

私の環境で、特定番組の音声が1番目にあったり、2番目にあったりとしたことがあり、うまく音声を読み込めないことがありました。そういった場合に使うことを想定しています。
修正は少しお待ち下さい。

**Comment by tobitti0** [comment]
修正しました。
`git pull origin master`で更新してから、`docker-compose up --build`を実行して、再度イメージを作成し直してください。
正常に動くはずです。

**Comment by yesimanoob** [comment]
修正してくださってありがとうございました。正常に動かせました！
