### ISSUE TITLE
相談：Trailer/Sponsor/Endcardの自動カット

### ISSUE THREAD

**Issue by yesimanoob** [tobitti0/JoinLogoScpTrialSetLinux#8]
あくまでご相談なのですが、JLファイル設定でTrailer/Sponsor/Endcardを自動カットにさせる方法が知りたいです。

JLScpは予告などの識別と位置を高精度で認識ができるのにどうすればその認識された部分を自動カットさせられるのが分かりません。

<details><summary>例：デフォルトのJL_標準でできたobs_jlscpとobs_cut</summary>
<pre><code>     0    186    6   7    0 :Nologo
   187    636   15   0    0 :CM
   637  34861 1142   0 1142 :L
 34863  35760   30  -1    0 :CM
 35761  36660   30   1    0 :CM
 36661  37109   15  -1    0 :CM
 37110  37559   15   0    0 :CM
 37560  38458   30   0    0 :CM
 38459  51405  432   0  432 :L
 51406  52304   30   0    0 :CM
 52305  52753   15  -1    0 :CM
 52754  53203   15   0    0 :CM
 53204  54102   30   0    0 :CM
 54103  55001   30   1    0 :CM
 55003  69177  473  -1  473 :L
 69178  69627   15   0    0 :CM
 69628  70076   15  -1    0 :CM
 70077  70526   15   0    0 :CM
 70527  70975   15  -1    0 :CM
 70976  71874   30   0    0 :CM
 71875  72324   15   0    0 :CM
 72325  72773   15   0    0 :CM
 72775  94292  718   0  718 :L
 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer
 94893  95041    5   0    5 :Trailer
 95043  95401   12  -1    0 :Sponsor(cut)
 95402  95491    3   0    0 :Endcard(add)
 95492  95940   15  -1    0 :CM
 95941  96390   15   0    0 :CM
 96391  96839   15  -1    0 :CM
 96840  97289   15   0    0 :CM
 97290  97738   15  -1    0 :CM
 97739  98188   15   0    0 :CM
 98189  98307    4  -1    0 :Nologo(cut)
 98308  98316    0   8    0 :Nologo
</br>
Trim(637,34861) ++ Trim(38459,51405) ++ Trim(55003,69177) ++ Trim(72775,95041) ++ Trim(95402,95491)
</code></pre></details>
Trailer/Sponsor/Endcardと認識されたフレームは完璧ですが、その部分はデフォルトで追加されています。
（cutとラベルがない限りは残る仕組みになっているようです）

JL_標準.txt内の設定をいじってみましたどうしてもカットにはできません。それぞれの設定を変えた結果が予想外で、期待していたものとは違っていました。とっても謎です。

試した設定変更と結果：
<details><summary><code>param_cuttr=1</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer
 94893  95041    5   0    5 :Trailer
 95043  95401   12  -1    0 :Sponsor(add)
 95402  95491    3   0    0 :Endcard(add)
</code></pre>
CutTRなのにSponsorがaddになりました。不思議です。</details>
<details><summary><code>param_cutsp=1</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer
 94893  95041    5   0    5 :Trailer
 95043  95401   12  -1    0 :Sponsor(cut)
 95402  95491    3   0    0 :Endcard(add)
</code></pre>
Sponsorはcutのまま、デフォルトと変わりなし。</details>
<details><summary><code>cuttr_limit=0</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer
 94743  94892    5   0    5 :Trailer
 94893  95041    5   0    5 :Trailer
 95043  95401   12  -1    0 :Sponsor(add)
 95402  95491    3   0    0 :Endcard(add)
</code></pre></details>
<details><summary><code>cuttr_limit=5</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer(add)
 94893  95041    5   0    5 :Trailer(add)
 95043  95401   12  -1    0 :Trailer(add)
 95402  95491    3   0    0 :Endcard(add)
</code></pre>
<code>cuttr_limit</code>はこう定義されています：
<code>予告と認識させる構成数（0:予告なし 1～:構成数）</code>が</br>JL_標準の下のほうでこう使われています：
<code>Default addtr_limit    $cuttr_limit    # 予告が見つからないと判断する必要予告構成数（0:制限なし 1～:構成数）</code></br>まったく理解できません。Cutの制限数はAddの制限数として使われています？０にしても５にしてもTrailerはCutになりません。
</details>
<details><summary><code>use_addtr=0</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer
 94893  95041    5   0    5 :Trailer
 95043  95401   12  -1    0 :Sponsor(add)
 95402  95491    3   0    0 :Endcard(add)
</code></pre></details>
<details><summary><code>param_cuttr=1 cuttr_limit=5</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer(add)
 94893  95041    5   0    5 :Trailer(add)
 95043  95401   12  -1    0 :Trailer(add)
 95402  95491    3   0    0 :Endcard(add)
</code></pre></details>
<details><summary><code>param_cuttr=1 param_cutsp=1 cuttr_limit=5</code></summary>
<pre><code> 94293  94742   15   0   15 :Trailer(add)
 94743  94892    5   0    5 :Trailer(add)
 94893  95041    5   0    5 :Trailer(add)
 95043  95401   12  -1    0 :Trailer(add)
 95402  95491    3   0    0 :Endcard(add)
</code></pre></details>

設定をどう変えればいいでしょうか？
Trailer/Sponsor/Endcardを自動カットすることができれば、私は非常に満足します！

**Comment by tobitti0** [comment]
私は基本的にJLSの1ユーザーでしかなく、JLは非常に複雑なこともありあまり詳しくはないです。
JLSは某掲示板のCMカットスレあたりで作られていたもので、そういったところのほうが詳しい方がおられると思います。

一般的には構成がすでにきちんと解析できている場合にカスタム動作させるときは、`JL_標準`ではなく`JL_フラグ指定`を使うのではないかと思います。
使い方は基本的に`join_logo_scp_trial`の`setting/設定内容.txt`に書いてあります。
[ここです。](https://github.com/tobitti0/join_logo_scp_trial/blob/72c077e41d0ae275c774e99a0751b7aa943ed24e/setting/%E8%A8%AD%E5%AE%9A%E5%86%85%E5%AE%B9.txt#L81-L153)
また、`JL_フラグ指定.txt`の中にコメントで書いてあります。こちらは実際にフラグの実装も見れるので、オリジナルのJLを0から作る場合は参考になると思います。
[ここです。](https://github.com/tobitti0/join_logo_scp/blob/0988f6a75d1d2c601044087992ba0596a53f5e09/JL/JL_%E3%83%95%E3%83%A9%E3%82%B0%E6%8C%87%E5%AE%9A.txt#L417-L455)

これらを読めばわかると思いますが、`JL_フラグ指定`で下記のようになると思います。
番組提供についてご希望どおりとするならば`#   ASPN   : 番組提供なし`になるかと思います。
同様にエンドカードについては`#   TCE    : エンドカードなしとする`になるかと思います。
予告についてはちょっとわからないですが、`#   TPTRLIM0  : 予告構成数=0`が使えるのではないでしょうか。

これらの使い方ですが、` JLparam_set1.csv`か`JLparam_set2.csv`を編集します。
` JLparam_set1.csv`は放送局単位で指定するもので、`JLparam_set2.csv`は番組単位で指定します。
`JLparam_set2.csv`にはネット上で配布されていたものを突っ込んだ記憶があるのでいくつか指定されています。
見ていただければだいたいつかめるかと思います。` JLparam_set1.csv`もほぼ同様の書き方です。
例えばチャンネル`BS11` 番組名`ANIME`、フラグを`フラグ`とすると`JLparam_set2.csv`は`BS11,ANIME,JL_フラグ指定.txt,"フラグ",,,,,,,,,`みたいにかけます。
番組名は正規表現で検出するので、実際のファイルに話数が入っていても問題ありません。
また、正規表現を使うこともできます。このあたりもWindowsのtrialとおなじになるように調整したので、[ここ](https://github.com/tobitti0/join_logo_scp_trial/blob/72c077e41d0ae275c774e99a0751b7aa943ed24e/setting/%E8%A8%AD%E5%AE%9A%E5%86%85%E5%AE%B9.txt#L47-L54)のとおりに使えると思います。
指定して`obs_param.txt`に指定結果が反映されていなければ私の検出プログラムミスかもしれませんが。

適当なアニメでJL_フラグ指定を試してみました。
<details>
<summary>とあるアニメの解析log　JL_標準</summary>
<pre>
<code>     0     76    3 -13    0 :Nologo
    77   1726   55   2   55 :L
  1727   4422   90  -1   90 :L
  4423   4722   10   0    0 :Sponsor(add)
  4723   5171   15  -1    0 :CM
  5172   5621   15   0    0 :CM
  5622   6070   15  -1    0 :CM
  6071   6520   15   0    0 :CM
  6521  20246  458   0  458 :L
 20247  21145   30   0    0 :CM
 21146  22044   30   0    0 :CM
 22045  23393   45   1   45 :L
 23395  40243  562   7  562 :L
 40245  42934   90  -7   90 :L
 42935  45630   90  -1   90 :L
 45631  45804    6  -5    6 :Trailer(add)
 45806  46173   12   9   12 :Sponsor(add)
 46175  46344    6  -9    6 :Endcard(add)
 46346  46530    6   5    6 :Trailer(cut)
 46531  47429   30   0    0 :CM
 47430  48328   30   0    0 :CM
 48329  48628   10   0    0 :Nologo(cut)
 48629  49077   15  -1    0 :CM
 49078  49527   15   0    0 :CM
 49528  53123  120   0    0 :CM
 53124  54023   30   1    0 :CM
 54024  54080    2  -4    0 :Nologo</code>
</pre>
</details>
提供やエンドカードなどがあります。
`ASPN,TCE`で提供とエンドカードを消してみます。
<details>
<summary>とあるアニメの解析log　JL_フラグ指定　ASPN,TCE</summary>
<pre>
<code>     0     76    3 -13    0 :Nologo
    77   1726   55   2   55 :L
  1727   4422   90  -1   90 :L
  4423   4722   10   0    0 :Nologo
  4723   5171   15  -1    0 :CM
  5172   5621   15   0    0 :CM
  5622   6070   15  -1    0 :CM
  6071   6520   15   0    0 :CM
  6521  20246  458   0  458 :L
 20247  21145   30   0    0 :CM
 21146  22044   30   0    0 :CM
 22045  23393   45   1   45 :L
 23395  40243  562   7  562 :L
 40245  42934   90  -7   90 :L
 42935  45630   90  -1   90 :L
 45631  45804    6  -5    6 :Trailer(add)
 45806  46173   12   9   12 :Trailer(cut)
 46175  46344    6  -9    6 :Trailer(cut)
 46346  46530    6   5    6 :Trailer(cut)
 46531  47429   30   0    0 :CM
 47430  48328   30   0    0 :CM
 48329  48628   10   0    0 :Nologo(cut)
 48629  49077   15  -1    0 :CM
 49078  49527   15   0    0 :CM
 49528  53123  120   0    0 :CM
 53124  54023   30   1    0 :CM
 54024  54080    2  -4    0 :Nologo</code>
</pre>
</details>

一個Trailerが残りました。とりあえず`TPTRLIM0`をつけてみます。
<details>
<summary>とあるアニメの解析log　JL_フラグ指定　ASPN,TCE</summary>
<pre>
<code>     0     76    3 -13    0 :Nologo
    77   1726   55   2   55 :L
  1727   4422   90  -1   90 :L
  4423   4722   10   0    0 :Nologo
  4723   5171   15  -1    0 :CM
  5172   5621   15   0    0 :CM
  5622   6070   15  -1    0 :CM
  6071   6520   15   0    0 :CM
  6521  20246  458   0  458 :L
 20247  21145   30   0    0 :CM
 21146  22044   30   0    0 :CM
 22045  23393   45   1   45 :L
 23395  40243  562   7  562 :L
 40245  42934   90  -7   90 :L
 42935  45630   90  -1   90 :L
 45631  45804    6  -5    6 :Trailer(cut)
 45806  46173   12   9   12 :Trailer(cut)
 46175  46344    6  -9    6 :Trailer(cut)
 46346  46530    6   5    6 :Trailer(cut)
 46531  47429   30   0    0 :CM
 47430  48328   30   0    0 :CM
 48329  48628   10   0    0 :Nologo(cut)
 48629  49077   15  -1    0 :CM
 49078  49527   15   0    0 :CM
 49528  53123  120   0    0 :CM
 53124  54023   30   1    0 :CM
 54024  54080    2  -4    0 :Nologo</code>
</pre>
</details>

最終的なTrim出力は次のとおりです。
`Trim(77,4422) ++ Trim(6521,20246) ++ Trim(22045,45630)`
ちゃんと消えました。
完成した`JLparam_set2.csv`は次のとおりです。
`BS11,たいとる,JL_フラグ指定.txt,"ASPN,TCE,TPTRLIM0",,,,,,,,,`

こんな感じにやっていくのではないかと思います。
私は基本的に`JL_標準`しか使わないので間違っていたらすみません。
詳しい指定については某掲示板の該当スレで聞くのがよいと思います。
JL等の指定方法はWindowsと何ら変わりませんので。
過去にはJL等の使い方を書いたサイトなどもあったと思いますので、ネットの海を探してみるのも良いかもしれません。

**Comment by yesimanoob** [comment]
ご丁寧な説明、ありがとうございます！フラグなどについて全然知りませんでした。

自分の環境で試してみて、`ASPN,TCE`のフラグだけですと最初の予告が残りました。そこで`TPTRLIM0`を追加して再度動かしてみましたが予告は残りました。しかし、別の動画ファイルにしたらちゃんと消えました。不思議ですが、とにかくフラグの使い方が分かって幸いです。もっといじってみます！

JLSの使い方についてさらに質問したい場合、どこの掲示板で聞くことがおすすめでしょうか？

**Comment by tobitti0** [comment]
DTV板のCMカットスレで開発されていたように思います。
ただ、質問して答えてくれる方がいるかはわかりませんが…
質問したことはないです。
過去スレなんかをたどると情報があるのではと思います。

**Comment by tobitti0** [comment]
質問Issueかつ、長期放置されていますので閉じさせていただきます。
